packaging_format = 2

id = "privatebin"
name = "PrivateBin"
description.en = "Pastebin where the server has zero knowledge of pasted data"
description.fr = "Pastebin où le serveur ignore les données copiées"

version = "2.0.3~ynh1"

maintainers = []

[upstream]
license = "Zlib"
website = "https://privatebin.info/"
demo = "https://privatebin.net/"
admindoc = "https://github.com/PrivateBin/PrivateBin/wiki"
code = "https://github.com/PrivateBin/PrivateBin"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/privatebin"

    [install.init_main_permission]
    ask.en = "Who should be able create new pastes? (This can be changed later)"
    type = "group"
    default = "all_users"

    [install.init_bins_permission]
    ask.en = "Who should be able to view previously created pastes? (This can be changed later)"
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de", "en", "es","fr", "it", "nl", "pl", "pt"]
    default = "fr"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrivateBin/PrivateBin/archive/refs/tags/2.0.3.tar.gz"
        sha256 = "378bca9982c3bee6288e7abb575b237ace2e1994b29d36f1fc8f966b9af0ff72"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"
    bins.additional_urls = ['re:\/\?[a-f0-9]{16}#[[:alnum:]]{44}$']

    [resources.apt]
    packages = "php8.4-gd, zlib1g-dev"
    